name: aquascan_v2
description: AquaScan Water Quality App
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.1.1
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  # google_maps_cluster_manager: ^3.1.0
  google_maps_flutter: ^2.12.3
  http: ^1.1.0
  image: ^4.1.3
  image_picker: ^1.0.4
  latlong2: ^0.9.1
  path: ^1.8.3
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  provider: ^6.1.1
  uuid: ^4.1.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
